### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by alpe12** [mariusmuntean/RouterAutomator#1]
Hi.
I know it's been some time since the last update, but this seems to be the only one to get close to what I want.
I have an Archer C7.

I need:
- The value of the post form data 'password' that is generated by the tplink login script (I couldn't reverse engineer it).
![image](https://user-images.githubusercontent.com/8551127/75626011-6ffe7c80-5ba2-11ea-8cc2-e72b9dfbe85f.png)

OR both of the following:
- The 'stok' value returned by the successful login request
![image](https://user-images.githubusercontent.com/8551127/75626420-34fe4800-5ba6-11ea-9c54-0ade01fa09d6.png)
- The value of the 'sysauth' cookie set on that same request
![image](https://user-images.githubusercontent.com/8551127/75626433-53644380-5ba6-11ea-82de-a79f02f2a0ef.png)

Preferably the first.

Can you, please, add an option to return this? Or if it's too easy send me another script just to achieve this?
It would help me a lot. Thanks.

PS: What I have here is an PHP page that does some stuff via PHP-Curl. But every time the router reboots I have to login myself on browser and save the "password" of the POST request and put it on my PHP. I have found no way to automate this, since I couldn't find out how the 'password' value is generated on the tp-link javascript and how to replicate it on PHP.

**Comment by alpe12** [comment]
I wrote myself a solution using Selenium.

**Comment by ahoffer** [comment]
> I wrote myself a solution using Selenium.

You wrote a Selenium solution? Can you post that Selenium solution in a gist?

**Comment by alpe12** [comment]
@ahoffer https://gist.github.com/alpe12/ee58362838192f5258b4bf62c2e53678
It saves the "stok" token to a file. And the cookies to another.
You can use these in another script to do pretty much anything.

Eg, to make the router ping some IP.
You have to load the cookies from the cookiesfile. On PHP you can do it in php-curl with:
```
CURLOPT_COOKIEFILE => 'cookies file location',
CURLOPT_COOKIEJAR => 'cookies file location'
```
And then you can open with php-curl:
```
url = 'http://192.168.1.254/cgi-bin/luci/;stok={CONTENTS_OF_TOKEN_FILE}/admin/diag?form=diag'
with POST_content = "operation=start;type=0;ipaddr_ping=10.8.0.1;ipaddr=10.8.0.1;count=1;pktsize=64"
```
